name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-frontend"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Configure git
        run: |
          git config --global user.name 'Luv Suneja'
          git config --global user.email 'luv@recalibr.ai'
        
      - name: Deploy to GitHub Pages
        working-directory: ./frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy -- --repo=https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
